---
title: "Model_Visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load required packages:
```{r}


suppressMessages(library(ggplot2))
suppressMessages(library(caret))
suppressMessages(library(ggpubr))
suppressMessages(library(MuMIn))
suppressMessages(library(lme4))
suppressMessages(library(feather))
suppressMessages(library(arrow))
suppressMessages(library(dplyr))
suppressMessages(library(viridis))
suppressMessages(library(scatterplot3d))
suppressMessages(library(graph3d))
suppressMessages(library(plot3D))
suppressMessages(library(magrittr))
suppressMessages(library(scales))

```


# Load the data:
```{r}

# Upload the data from a total data file:
total_data <- read.csv("MODEL_DATA.csv")

# Input required files into function:
regional_data <- Read_fn("MODEL_DATA.csv")  # Regional
global_data <- Read_fn("MODEL_DATA_GLOBAL.csv")  # Global

final_data <- read.csv("MODEL_DATA_GLOBAL_FINAL.csv") %>% 
    mutate(Bloom = if_else(Chl > 2.5, 1, 0)) %>% 
    select(TEP, Chl, Log_Chl, Temperature, Bloom, Arctic, Area)

```


# Make a basic 3D visualization between the most important parameters:
```{r}

scatterplot3d(x = global_data$Log_Chl, y = global_data$Temperature, z = global_data$TEP, pch = 16,
              xlab = "Chlorophyll a (log-scale)", ylab = "Temperature (˚C)", zlab = "TEP")

ggplot(final_data, aes(Log_Chl, TEP, colour = Area)) +
  geom_point() +
  geom_smooth(method = 'lm')

```


# Make a more advanced 3D visualization between the most important parameters:
```{r}

# Create the model to visualize:
global_data %>% lm(TEP ~ Log_Chl + Temperature, data = .) -> fit

grid.lines = 20 # vis parameter

# Grid parameters:
x.pred = seq(min(global_data$Log_Chl), 
             max(global_data$Log_Chl), length.out= grid.lines)

y.pred = seq(min(global_data$Temperature), 
             max(global_data$Temperature), length.out = grid.lines)

xy = expand.grid(Log_Chl = x.pred, 
                 Temperature = y.pred)

z.pred = matrix(predict(fit, newdata = xy), 
                nrow = grid.lines, ncol = grid.lines)

# Prediction points:
fitpoints = predict(fit)


# Visualization 1:
global_data %$% scatter3D(Log_Chl, Temperature, TEP, pch = 19, cex = 0.5, 
                  theta = 35, phi = 15, bty="b", colvar=FALSE, col="red",
                  expand = 0.7, 
                  xlab = "Chlorophyll a (log-scale)", ylab = "Temperature (˚C)", 
                  zlab = "TEP", clab = "TEP",
                  surf = list(x = x.pred, y = y.pred, z = z.pred,  
                                facets = NA, fit = fitpoints, col = "black"))



# Visualization 2:
global_data %$% scatter3D(Log_Chl, Temperature, TEP, pch = 18, cex = 1, 
                    colvar=FALSE, col="red", theta = 25, phi = 20, bty="u",
                    col.panel ="azure2", expand =0.5, col.grid = "snow",
                    xlab = "Chlorophyll a (log-scale)", ylab = "Temperature (˚C)", zlab = "TEP",  
                    surf = list(x = x.pred, y = y.pred, z = z.pred,  
                    facets = TRUE, col=ramp.col (col = c("yellow","darkorange"), 
                                n = 100, alpha=0.7), fit = fitpoints, border="black"))


# Visualization 3:
global_data %$% scatter3D(Log_Chl, Temperature, TEP, pch = 19, cex = 0.5, 
                  theta = 35, phi = 15, bty="b",
                  expand =0.7, 
                  xlab = "Chlorophyll a (log-scale)", ylab = "Temperature (˚C)", 
                  zlab = "TEP", clab = "TEP",
                  surf = list(x = x.pred, y = y.pred, z = z.pred,  
                                facets = NA, fit = fitpoints),
                  colkey = list(side = 4, length = 0.7, width = 0.5, 
                                line.clab = 0.5, adj.clab = 0, dist = -0.05))




```


# Reconfirm validity of temperature influence with bloom as a factor:
```{r}

ggplot(global_data, aes(Temperature, TEP, colour = as.factor(Bloom))) + 
  geom_point() +
  geom_smooth(method = 'lm')


summary(lm(TEP ~ Temperature + Bloom, data = global_data))



```


# Quick comparison between datasets:
```{r}

# Upload the data from a total data file:
OG_data <- read.csv("MODEL_DATA_GLOBAL.csv")
NEW_data <- read.csv("MODEL_DATA_GLOBAL_FINAL.csv")



ggplot(OG_data, aes(Log_Chl, TEP, color = Area)) +
  geom_point()
summary(lm(TEP ~ Chl, data = OG_data))


ggplot(NEW_data, aes(Chl, TEP)) +
  geom_point() +
  geom_smooth(method = 'lm') +
  scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) +
  #ylim(0, 150) +
  annotation_logticks(sides = 'b')


ggplot(NEW_data, aes(Chl, TEP)) +
  geom_point() +
  geom_smooth() +
  ylim(0, 150) +
  annotation_logticks(sides = 'b')

summary(lm(TEP ~ Chl, data = NEW_data))

```

